# Generated by Django 3.1.7 on 2021-03-04 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipe',
            new_name='RecipeRequirement',
        ),
    ]
