# Generated by Django 3.1.7 on 2021-03-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210304_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciperequirement',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
